services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
